apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong-injector.fullname" . }}
  labels:
    {{- include "kong-injector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kong-injector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kong-injector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kong-injector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: KONG_ADMIN_URL
              value: {{ .Values.env.kongAdminUrl }}
            - name: KONG_ADMIN_PORT
              value: "{{ .Values.env.kongAdminPort }}"
            - name: KONG_NAMESPACE
              value: {{ .Values.env.kongNamespace }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: kong-config
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: {{ .Values.configMap.readOnly }}
      volumes:
        - name: kong-config
          configMap:
            name: {{ .Values.configMap.name }}

